name: Build amneziawg-kmod source archive

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
          contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Preparing environment
        run: |
          sudo apt-get update
          sudo apt-get install quilt dpkg-dev xz-utils -y
    
      - name: Parse version and release
        id: version
        run: |
          TAG=${GITHUB_REF_NAME#v}
          UPSTREAM=${TAG%-*}
          RELEASE=${TAG##*-}
          UPSTREAM_TOOLS=1.0.20260223
          echo "upstream=$UPSTREAM" >> $GITHUB_OUTPUT
          echo "upstream_tools=$UPSTREAM_TOOLS" >> $GITHUB_OUTPUT
          echo "release=$RELEASE" >> $GITHUB_OUTPUT

      - name: Download upstream source
        run: |
          wget -O source.tar.gz \
            "https://github.com/amnezia-vpn/amneziawg-linux-kernel-module/archive/refs/tags/v${{ steps.version.outputs.upstream }}.tar.gz"
          wget -O source-tools.tar.gz \
            "https://github.com/amnezia-vpn/amneziawg-tools/archive/refs/tags/v${{ steps.version.outputs.upstream_tools }}.tar.gz"

      - name: Extract and repack
        run: |
          tar -xzf source.tar.gz
          tar -xzf source-tools.tar.gz
          rm -rf amneziawg-linux-kernel-module-${{ steps.version.outputs.upstream }}/debian
          rm -rf amneziawg-tools-${{ steps.version.outputs.upstream_tools }}/debian

          cd amneziawg-linux-kernel-module-${{ steps.version.outputs.upstream }}/src
          rm -rf dkms.conf
          cat > dkms.conf << EOF
          PACKAGE_NAME="amneziawg"
          PACKAGE_VERSION="${{ steps.version.outputs.upstream_tools }}"
          AUTOINSTALL=yes
          
          BUILT_MODULE_NAME="amneziawg"
          DEST_MODULE_LOCATION="/kernel/drivers/net/wireguard"
          PRE_BUILD="pre-build.sh"
          EOF
          cd ../../

          
          cp -r blake2sintegrationMakefile.patch fixmemleakinjpspecsetup.patch fixversionkernel.patch debian/patches
          cp -r debian amneziawg-linux-kernel-module-${{ steps.version.outputs.upstream }}/
          cd amneziawg-linux-kernel-module-${{ steps.version.outputs.upstream }} && export QUILT_PATCHES=debian/patches && quilt push -a && rm -rf .pc && cd ../

          mkdir amneziawg-linux-kmod_${{ steps.version.outputs.upstream }}
          rm -rf amneziawg-linux-kernel-module-${{ steps.version.outputs.upstream }}/debian/patches       
          cp -r amneziawg-linux-kernel-module-${{ steps.version.outputs.upstream }}/src/* amneziawg-linux-kernel-module-${{ steps.version.outputs.upstream }}/COPYING blake2s.patch pre-build.sh amneziawg-linux-kmod_${{ steps.version.outputs.upstream }}/
          tar -czvf amneziawg-linux-kmod_${{ steps.version.outputs.upstream }}.orig.tar.gz amneziawg-linux-kmod_${{ steps.version.outputs.upstream }}
          cp -r amneziawg-linux-kmod_${{ steps.version.outputs.upstream }} amneziawg-linux-kmod
          tar -czvf amneziawg-kmod.tar.gz amneziawg-linux-kmod
          cd amneziawg-linux-kernel-module-${{ steps.version.outputs.upstream }}
          tar -czvf amneziawg-linux-kmod_${{ steps.version.outputs.upstream }}-${{ steps.version.outputs.release }}.debian.tar.gz debian
          mv amneziawg-linux-kmod_${{ steps.version.outputs.upstream }}-${{ steps.version.outputs.release }}.debian.tar.gz ../
          cd ../

          cp -r fixversiontools.patch debian_awgtools/patches/
          cp -r debian_awgtools amneziawg-tools-${{ steps.version.outputs.upstream_tools }}/debian
          cd amneziawg-tools-${{ steps.version.outputs.upstream_tools }} && export QUILT_PATCHES=debian/patches && quilt push -a && rm -rf .pc && cd ../
          
          mkdir amneziawg_${{ steps.version.outputs.upstream_tools }}
          rm -rf amneziawg-tools-${{ steps.version.outputs.upstream_tools }}/debian/patches       
          cp -r amneziawg-tools-${{ steps.version.outputs.upstream_tools }}/src amneziawg-tools-${{ steps.version.outputs.upstream_tools }}/contrib amneziawg-tools-${{ steps.version.outputs.upstream_tools }}/COPYING amneziawg_${{ steps.version.outputs.upstream_tools }}/
          tar -czvf amneziawg_${{ steps.version.outputs.upstream_tools }}.orig.tar.gz amneziawg_${{ steps.version.outputs.upstream_tools }}
          cp -r amneziawg_${{ steps.version.outputs.upstream_tools }} amneziawg-tools-${{ steps.version.outputs.upstream_tools }}
          tar -czvf amneziawg-tools.tar.gz amneziawg-tools-${{ steps.version.outputs.upstream_tools }}
          cd amneziawg-tools-${{ steps.version.outputs.upstream_tools }}
          tar -czvf amneziawg_${{ steps.version.outputs.upstream_tools }}-${{ steps.version.outputs.release }}.debian.tar.gz debian
          mv amneziawg_${{ steps.version.outputs.upstream_tools }}-${{ steps.version.outputs.release }}.debian.tar.gz ../
          cd ../

          MD5orig=$(md5sum amneziawg-linux-kmod_${{ steps.version.outputs.upstream }}.orig.tar.gz | cut -d ' ' -f1)
          MD5debian=$(md5sum amneziawg-linux-kmod_${{ steps.version.outputs.upstream }}-${{ steps.version.outputs.release }}.debian.tar.gz | cut -d ' ' -f1)
          SHA256orig=$(sha256sum amneziawg-linux-kmod_${{ steps.version.outputs.upstream }}.orig.tar.gz | cut -d ' ' -f1)
          SHA256debian=$(sha256sum amneziawg-linux-kmod_${{ steps.version.outputs.upstream }}-${{ steps.version.outputs.release }}.debian.tar.gz | cut -d ' ' -f1)
          SIZEorig=$(wc -c < amneziawg-linux-kmod_${{ steps.version.outputs.upstream }}.orig.tar.gz)
          SIZEdebian=$(wc -c < amneziawg-linux-kmod_${{ steps.version.outputs.upstream }}-${{ steps.version.outputs.release }}.debian.tar.gz)

          cat > amneziawg-kmod.dsc << EOF
          Format: 3.0 (quilt)
          Source: amneziawg-linux-kmod
          Binary: amneziawg-dkms
          Version: ${{ steps.version.outputs.upstream }}-${{ steps.version.outputs.release }}
          Maintainer: Oleg YroriXW <olegyrori@gmail.com>
          Architecture: all
          Vcs-Git: https://github.com/YroriXW/amneziawg.git
          Vcs-Browser: https://github.com/YroriXW/amneziawg
          Build-Depends: debhelper-compat (= 13), dh-dkms, dkms
          Standards-Version: 4.7.2
          Package-List:
            amneziawg-dkms deb kernel optional arch=all    
          Homepage: https://amnezia.org
          Files:
           ${MD5orig} ${SIZEorig} amneziawg-linux-kmod_${{ steps.version.outputs.upstream }}.orig.tar.gz
           ${MD5debian} ${SIZEdebian} amneziawg-linux-kmod_${{ steps.version.outputs.upstream }}-${{ steps.version.outputs.release }}.debian.tar.gz
          Checksums-Sha256:
           ${SHA256orig} ${SIZEorig} amneziawg-linux-kmod_${{ steps.version.outputs.upstream }}.orig.tar.gz
           ${SHA256debian} ${SIZEdebian} amneziawg-linux-kmod_${{ steps.version.outputs.upstream }}-${{ steps.version.outputs.release }}.debian.tar.gz
          EOF

          MD5orig=$(md5sum amneziawg_${{ steps.version.outputs.upstream_tools }}.orig.tar.gz | cut -d ' ' -f1)
          MD5debian=$(md5sum amneziawg_${{ steps.version.outputs.upstream_tools }}-${{ steps.version.outputs.release }}.debian.tar.gz | cut -d ' ' -f1)
          SHA256orig=$(sha256sum amneziawg_${{ steps.version.outputs.upstream_tools }}.orig.tar.gz | cut -d ' ' -f1)
          SHA256debian=$(sha256sum amneziawg_${{ steps.version.outputs.upstream_tools }}-${{ steps.version.outputs.release }}.debian.tar.gz | cut -d ' ' -f1)
          SIZEorig=$(wc -c < amneziawg_${{ steps.version.outputs.upstream_tools }}.orig.tar.gz)
          SIZEdebian=$(wc -c < amneziawg_${{ steps.version.outputs.upstream_tools }}-${{ steps.version.outputs.release }}.debian.tar.gz)

          cat > amneziawg.dsc << EOF
          Format: 3.0 (quilt)
          Source: amneziawg
          Binary: amneziawg
          Version: ${{ steps.version.outputs.upstream_tools }}-${{ steps.version.outputs.release }}
          Maintainer: Oleg YroriXW <olegyrori@gmail.com>
          Architecture: all
          Vcs-Git: https://github.com/amnezia-vpn/amnezia-wg-tools.git
          Vcs-Browser: https://github.com/amnezia-vpn/amnezia-wg-tools
          Build-Depends: debhelper-compat (= 13), pkg-config, systemd
          Standards-Version: 4.7.2
          Package-List:
            amneziawg deb net optional arch=all
          Homepage: https://amnezia.org
          Files:
           ${MD5orig} ${SIZEorig} amneziawg_${{ steps.version.outputs.upstream_tools }}.orig.tar.gz
           ${MD5debian} ${SIZEdebian} amneziawg_${{ steps.version.outputs.upstream_tools }}-${{ steps.version.outputs.release }}.debian.tar.gz
          Checksums-Sha256:
           ${SHA256orig} ${SIZEorig} amneziawg_${{ steps.version.outputs.upstream_tools }}.orig.tar.gz
           ${SHA256debian} ${SIZEdebian} amneziawg_${{ steps.version.outputs.upstream_tools }}-${{ steps.version.outputs.release }}.debian.tar.gz
          EOF

          cat > amneziawg-tools.dsc << EOF
          Format: 3.0 (quilt)
          Source: amneziawg
          Binary: amneziawg-tools
          Version: ${{ steps.version.outputs.upstream_tools }}-${{ steps.version.outputs.release }}
          Maintainer: Oleg YroriXW <olegyrori@gmail.com>
          Architecture: all
          Vcs-Git: https://github.com/amnezia-vpn/amnezia-wg-tools.git
          Vcs-Browser: https://github.com/amnezia-vpn/amnezia-wg-tools
          Build-Depends: debhelper-compat (= 13), pkg-config, systemd
          Standards-Version: 4.7.2
          Package-List:
            amneziawg-tools deb net optional arch=all
          Homepage: https://amnezia.org          
          Files:
           ${MD5orig} ${SIZEorig} amneziawg_${{ steps.version.outputs.upstream_tools }}.orig.tar.gz
           ${MD5debian} ${SIZEdebian} amneziawg_${{ steps.version.outputs.upstream_tools }}-${{ steps.version.outputs.release }}.debian.tar.gz
          Checksums-Sha256:
           ${SHA256orig} ${SIZEorig} amneziawg_${{ steps.version.outputs.upstream_tools }}.orig.tar.gz
           ${SHA256debian} ${SIZEdebian} amneziawg_${{ steps.version.outputs.upstream_tools }}-${{ steps.version.outputs.release }}.debian.tar.gz
          EOF

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            amneziawg-linux-kmod_${{ steps.version.outputs.upstream }}.orig.tar.gz
            amneziawg-linux-kmod_${{ steps.version.outputs.upstream }}-${{ steps.version.outputs.release }}.debian.tar.gz
            amneziawg_${{ steps.version.outputs.upstream_tools }}.orig.tar.gz
            amneziawg_${{ steps.version.outputs.upstream_tools }}-${{ steps.version.outputs.release }}.debian.tar.gz
            amneziawg-kmod.tar.gz
            amneziawg-tools.tar.gz
            amneziawg-kmod.dsc
            amneziawg-tools.dsc
            amneziawg.dsc
